package com.example.evan.androidviewertemplates.utils;

import android.util.Log;

import com.example.evan.androidviewertools.utils.Constants;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class SpecificConstants extends Constants {
    //todo
    public static Map<String, String> KEYS_TO_TITLES;
    public static Map<String, String> DATA_TO_GRAPH;
    public static Map<String, String> DATA_COMPARISON_TEAMS_NORMAL;
    public static Map<String, String> DATA_COMPARISON_TEAMS_SD;
    public static Map<String, String> DATA_COMPARISON_TEAMS_LFM;
    public static Map<String, String> DATA_COMPARISON_TEAMS_P75;
    public static Map<String, String> DATA_COMPARISON_TIMD;
    public static List<String> CATEGORY_LIST;

    //todo
    public static final String[] DRAWER_TITLES = {"Schedule", "Upcoming Matches", "Recent Matches", "Starred Matches", "Our Schedule", "Seeding", "Data Comparison", "First Pick", "Second Pick","Third Pick","Super Data", "Live Picklist", "Highlighting"};
    public static final String ORIGINAL_ROOT_FIREBASE_PATH = "https://scouting-2019-cmp-d43a4.firebaseio.com/";
    public static String ROOT_FIREBASE_PATH = ORIGINAL_ROOT_FIREBASE_PATH;
    public static String MATCHES_PATH = ORIGINAL_ROOT_FIREBASE_PATH + "Matches";
    public static String TEAMS_PATH = ORIGINAL_ROOT_FIREBASE_PATH + "Teams";
    public static String TEAM_IN_MATCH_DATAS_PATH = ORIGINAL_ROOT_FIREBASE_PATH + "TIMDs";

    static {
        Map<String, String> initialKeysToTitlesMap = new HashMap<String, String>() {
            {
                put("matches", "Matches");
                put("VIEWER.matchesUntilNextMatchForTeam", "Matches Until Next Match");
//                put("calculatedData.numMatchesPlayed", "Num. Matches Played");
                put("lfm", "Last Four Matches");
                put("matchNumber", "Match Number");
                put("startingLevel","Starting level");
                put("crossedHabLine","Crossed HAB line");
                put("startingLocation","Starting location");
                put("calculatedData.pointsPrevented", "Points prevented in the match");
                put("calculatedData.cargoPointsPrevented", "Cargo pts prevented in the match");
                put("calculatedData.panelPointsPrevented", "Panel pts prevented in the match");
                put("preload","Preloaded game piece");
                put("driverStation","Driver station ");
                put("isNoShow","Did not show up to match");
                put("calculatedData.cargoScored","# cargo scored");
                put("calculatedData.panelsScored","# panel scored");
                put("calculatedData.cargoFouls","Cargo fouls out of field");
                put("calculatedData.panelLoadSuccess","LS intake success %");
                put("calculatedData.cargoCycleAll","Avg cargo in RS/CS");
                put("cargoCycleL1","Avg cargo L1 RS/CS");
                put("cargoCycleL2","Avg cargo L2 RS");
                put("cargoCycleL3","Avg cargo L3 RS");
                put("calculatedData.panelCycleAll","Avg hatch in RS/CS");
                put("panelCycleL1","Avg panel L1 RS/CS");
                put("panelCycleL2","Avg panel L2 RS");
                put("panelCycleL3","Avg panel L3 RS");
                put("cargoSuccessAll","% cargo total success");
                put("calculatedData.cargoSuccessDefended","% cargo defend success");
                put("cargoSuccessUndefended","% cargo undefended success");
                put("cargoSuccessL1","% cargo success L1 RS/CS");
                put("calculatedData.cargoSuccessL2","% cargo success L2 RS");
                put("calculatedData.cargoSuccessL3","% cargo success L3 RS");
                put("panelSuccessAll","% panel total success");
                put("calculatedData.panelSuccessDefended","% panel defend success");
                put("panelSuccessUndefended","% panel undefended success");
                put("calculatedData.panelSuccessL1","% panel success L1");
                put("calculatedData.panelSuccessL2","% panel success L2");
                put("calculatedData.panelSuccessL3","% panel success L3");
                put("calculatedData.timeIncap","Time incap (% of match)");
                put("calculatedData.timeClimbing","Time climbing (s)");
                put("calculatedData.pinningFouls","Pinning Fouls");
                put("calculatedData.selfClimbLevel","Climb Level");
                put("notes","Super Notes");
                put("calculatedData.robot1ClimbLevel","1st Robot Climb Level");
                put("calculatedData.robot2ClimbLevel","2nd Robot Climb Level");
                put("calculatedData.panelsScoredTeleL1","Lvl 1 panels placed");
                put("calculatedData.panelsScoredTeleL2","Lvl 2 panels placed");
                put("calculatedData.panelsScoredTeleL3","Lvl 3 panels placed");
                put("calculatedData.cargoScoredTeleL1","Lvl 1 cargo placed");
                put("calculatedData.cargoScoredTeleL2","Lvl 2 cargo placed");
                put("calculatedData.cargoScoredTeleL3","Lvl 3 cargo placed");
                put("calculatedData.totalFailedCyclesCaused","Total Cycles Defended");
                put("calculatedData.avgRankDefense","Avg Rank Defense");
                put("rankDefense","Rank Defense");
                put("calculatedData.avgRankCounterDefense","Avg Counter Defense");
                put("calculatedData.avgFailedCyclesCaused","Avg Cycles Defended");
                put("calculatedData.timeDefending","Time defending");
                put("calculatedData.totalTimeDefending","Total Time Defending");
                put("calculatedData.avgTimeDefending","Avg Time Defending");
                put("calculatedData.failedCyclesCaused","Cycles Defended");
                put("calculatedData.failedCyclesCausedPerSecond","Cycles Defended Per Second");
                put("calculatedData.habLineAttemptsL1","HAB line attempts L1");
                put("calculatedData.habLineAttemptsL2","HAB line attempts L2");
                put("calculatedData.avgPointsPrevented","Avg Points Prevented");
                put("calculateDData.cargoSuccessDefended","cargoSuccessDefended");
                put("calculatedData.pointsPrevented","Points Prevented");
                put("calculatedData.avgCargoPointsPrevented","Avg Cargo Points Prevented");
                put("calculatedData.avgPanelPointsPrevented","Avg Panel Points Prevented");
                put("calculatedData.pushAbility","Push Ability");

//              Teams
                put("pitDriveTrainMotorType","Drive Train Motor Type");
                put("pitNumDriveTrainMotors","Num. Drive Train Motors");
                put("pitWeight", "Weight");
                put("pitWheelDiameter", "Wheel diameter");
                put("pitDrivetrain", "Drive train");
                put("pitProgrammingLanguage", "Programming language");
                put("pitClimbType", "Climb type");
                put("pitHasCamera", "Has camera");
                put("pitHasPid", "Has pid");
                put("pitSEALsNotes", "SEALsNotes");
                put("teamNumber", "Team #");
                put("name", "Team name");
                put("actualRPs", "Total # RP");
                put("matchesPlayed", "Matches played");
                put("actualSeed", "Seed");
                put("predictedRPs", "Predicted PRs");
                put("predictedSeed", "Predicted seed");
                put("calculatedData.hasCargoGroundIntake", "Has cargo ground intake");
                put("calculatedData.hasPanelGroundIntake", "Has panel ground intake");
                put("didPreloadPanel", "Preloaded panel at least once");
                put("calculatedData.avgCargoScored", "Avg cargo scored");
                put("calculatedData.avgPanelsScored", "Avg hatch scored");
                put("calculatedData.avgCargoFouls", "Avg cargo fouls out of field");
                put("panelSuccessFromSide", "Far side RS or side CS placements");
                put("calculatedData.habLineSuccessL1", "% HAB line from L1 success");
                put("calculatedData.habLineSuccessL2", "% HAB line from L2 success");
                put("calculatedData.avgTimeIncap", "Avg incap time");
                put("calculatedData.avgTimeClimbing", "Avg climbing time");
                put("calculatedData.percentIncap", "% incap");
                put("calculatedData.percentNoShow", "% no show");
                put("predictedDedicatedPanelCycles", "Predicted only panel cycles");
                put("predictedDedicatedCargoCycles", "Predicted only cargo");
                put("calculatedData.predictedSoloPoints", "Predicted points by team (alone)");
                put("cargoAbility", "Cargo ability");
                put("panelAbility", "Panel ability");
                put("calculatedData.firstPickAbility", "First pick ability");
                put("calculatedData.secondPickAbility", "Second pick ability");
                put("calculatedData.thirdPickAbility","Third Pick Ability");
                put("calculatedData.avgPinningFouls", "Avg pinning fouls");
                put("calculatedData.avgPanelsScoredSandstorm", "Avg panels placed during Sandstorm");
                put("calculatedData.avgCargoScoredSandstorm", "Avg cargo placed during Sandstorm");
                put("calculatedData.driverAbility", "Driver ability");
                put("calculatedData.climbSuccessL1", "% Climb success for HAB L1");
                put("calculatedData.climbSuccessL2", "% Climb success for HAB L2");
                put("calculatedData.climbSuccessL3", "% Climb success for HAB L3");
                put("pitSEALsRampRanking", "Ramp Ability");
                put("calculatedData.climbAttemptsL1", "Climb Attempt L1");
                put("calculatedData.climbAttemptsL2", "Climb Attempt L2");
                put("calculatedData.climbAttemptsL3", "Climb Attempt L3");
                put("calculatedData.cargoScoredL1", "Cargo Scored in L1");
                put("calculatedData.percentDysfunctional", "% dysfunctional");
                put("pitIsPanelSpecialist", "Is Panel Specialist");
                //lfm
                put("calculatedData.lfmAvgCargoScored", "Avg cargo scored");
                put("calculatedData.lfmAvgPanelsScored", "Avg panel scored");
                put("calculatedData.lfmAvgCargoFouls", "Avg cargo fouls");
                put("calculatedData.lfmPanelLoadSuccess", "Panel LS success");
                put("calculatedData.lfmCargoCycleAll", "Time cargo in RS");
                put("lfmCargoCycleL1", "Avg cargo L1 RS/CS");
                put("lfmCargoCycleL2", "Avg cargo L2 RS");
                put("lfmCargoCycleL3", "Avg cargo L3 RS");
                put("calculatedData.lfmPanelCycleAll", "Time panels in RS");
                put("lfmPanelCycleL1", "Avg panel L1 RS");
                put("lfmPanelCycleL2", "Avg panel L2 RS");
                put("lfmPanelCycleL3", "Avg panel L3 RS");
                put("lfmCargoSuccessAll", "Cargo all success");
                put("calculatedData.lfmCargoSuccessDefended", "Cargo defended success");
                put("lfmCargoSuccessUndefended", "Cargo undefended success");
                put("lfmCargoSuccessL1", "Avg panel L1 success");
                put("calculatedData.lfmCargoSuccessL2", "Avg panel L2 success");
                put("calculatedData.lfmCargoSuccessL3", "Avg panel L3 success");
                put("lfmPanelSuccessAll", "Avg panel all success");
                put("calculatedData.lfmPanelSuccessDefended", "Avg panel defended success");
                put("lfmPanelSuccessUndefended", "Avg panel undefended success");
                put("lfmPanelSuccessL1", "Avg panel L1 success");
                put("calculatedData.lfmPanelSuccessL2", "Avg panel L2 success");
                put("calculatedData.lfmPanelSuccessL3", "Avg panel L3 success");
                put("lfmPanelSuccessFromSide", "Avg far side RS or side CS placement");
                put("calculatedData.lfmHabLineSuccessL1", "HAB line success start from L1");
                put("calculatedData.lfmHabLineSuccessL2", "HAB line success start from L2");
                put("calculatedData.lfmAvgTimeIncap", "Avg time incap");
                put("calculatedData.lfmAvgTimeClimbing", "Avg time climbing");
                put("calculatedData.lfmPercentIncap", "% incap");
                put("calculatedData.lfmPercentNoShow", "% no show");
                put("lfmAvgPinningFouls", "Avg panels spilled");
                //sd
                put("calculatedData.sdAvgCargoScored", "SD avg cargo scored");
                put("calculatedData.sdAvgPanelsScored", "SD avg hatch scored");
                put("sdAvgCargoFouls", "Avg cargo fouls");
                put("sdPanelLoadSuccess", "Avg panel LS success");
                put("sdCargoCycleAll", "Avg cargo in RS/CS");
                put("sdCargoCycleL1", "Avg cargo in L1 RS/CS");
                put("sdCargoCycleL2", "Avg cargo in L2 RS");
                put("sdCargoCycleL3", "Avg cargo in L3 RS");
                put("sdPanelCycleAll", "Avg panel in RC/CS");
                put("sdPanelCycleL1", "Avg panel in L1 RC/CS");
                put("sdPanelCycleL2", "Avg panel in L2 RC/CS");
                put("sdPanelCycleL3", "Avg panel in L3 RC/CS");
                put("sdCargoSuccessAll", "Avg cargo all success");
                put("sdCargoSuccessDefended", "Avg cargo defended success");
                put("sdCargoSuccessUndefended", "Avg cargo undefended success");
                put("sdCargoSuccessL1", "Avg cargo success L1");
                put("sdCargoSuccessL2", "Avg cargo success L2");
                put("sdCargoSuccessL3", "Avg cargo success L3");
                put("sdPanelSuccessAll", "Avg panel all success");
                put("sdPanelSuccessDefended", "Avg panel defended success");
                put("sdPanelSuccessUndefended", "Avg panel undefended success");
                put("sdPanelSuccessL1", "Avg cargo success L1");
                put("sdPanelSuccessL2", "Avg cargo success L2");
                put("sdPanelSuccessL3", "Avg cargo success L3");
                put("sdPanelSuccessFromSide", "Avg far side RS or side CS placement");
                put("sdHabLineSuccessL1", "HAB line success start from L1");
                put("sdHabLineSuccessL2", "HAB line success start from L2");
                put("sdAvgTimeIncap", "Avg time incap");
                put("sdAvgTimeClimbing", "Avg time climbing");
                put("sdPercentIncap", "% incap");
                put("sdPercentNoShow", "% no show");
                put("calculatedData.sdAvgPinningFouls", "Avg panels spilled");
                //p75
                put("p75avgCargoScored", "Avg cargo scored");
                put("calculatedData.p75avgPanelsScored", "Avg panels scored");
                put("p75avgCargoFouls", "Avg cargo foul out of field");
                put("p75panelLoadSuccess", "Panel LS success");
                put("p75cargoCycleAll", "Avg cargo in RS/CS");
                put("p75cargoCycleL1", "Avg cargo in L1 RS");
                put("p75cargoCycleL2", "Avg cargo in L2 RS");
                put("p75cargoCycleL3", "Avg cargo in L3 RS");
                put("p75panelCycleAll", "Avg panel in RS/CS");
                put("p75panelCycleL1", "Avg panel in L1 RS");
                put("p75panelCycleL2", "Avg panel in L2 RS");
                put("p75panelCycleL3", "Avg panel in L3 RS");
                put("p75cargoSuccessAll", "Avg cargo all success");
                put("p75cargoSuccessDefended", "Avg cargo defended success");
                put("p75cargoSuccessUndefended", "Avg cargo undefended success");
                put("p75cargoSuccessL1", "Avg cargo success in L1 RS");
                put("p75cargoSuccessL2", "Avg cargo success in L2 RS");
                put("p75cargoSuccessL3", "Avg cargo success in L3 RS");
                put("p75panelSuccessAll", "Avg panel all success");
                put("p75panelSuccessL1", "Avg panel success in L1 RS");
                put("p75panelSuccessL2", "Avg panel success in L2 RS");
                put("p75panelSuccessL3", "Avg panel success in L3 RS");
                put("p75panelSuccessFromSide", "Avg panel success from side");
                put("p75habLineSuccessL1", "HAB line success start from L1");
                put("p75habLineSuccessL2", "HAB line success start from L2");
                put("p75avgTimeIncap", "Avg time incap");
                put("p75avgTimeClimbing", "Avg time climbing");
                put("p75percentIncap", "% incap");
                put("p75percentNoShow", "% no show");
                put("p75AvgPinningFouls", "Avg panels spilled");
//              Matches
                put("cargoShipPreload", "Cargo ship preload");
                put("blueTeams", "Blue alliance teams");
                put("redTeams", "Red alliance teams");
                put("noShowTeams", "No show teams");
                put("blueActualScore", "Blue score");
                put("redActualScore", "Red score");
                put("blueFoulPoints", "Blue fouls points gained");
                put("redFoulPoints", "Red fouls points gained");
                put("blueActualRPs", "Blue total RP");
                put("redActualRPs", "Red total RP");
                put("blueDidRocketRP", "Blue rocket RP");
                put("redDidRocketRP", "Red rocket RP");
                put("blueDidClimbRP", "Blue climb RP");
                put("redDidClimbRP", "Red climb RP");
                put("blueChanceRocketRP", "Blue chance rocket RP");
                put("redChanceRocketRP", "Red chance rocket RP");
                put("blueChanceClimbRP", "Blue chance climb RP");
                put("redChanceClimbRP", "Red chance climb RP");
                put("bluePredictedScore", "Blue predicted score");
                put("redPredictedScore", "Red predicted score");
                put("blueChanceWin", "Blue chance win");
                put("redChanceWin", "Red chance win");
                put("bluePredictedClimbPoints", "Blue predicted climb points");
                put("redPredictedClimbPoints", "Red predicted climb points");
//            SuperData
                put("calculatedData.speedZScore", "Speed Z Score");
                put("calculatedData.agilityZScore", "Agility Z Score");
//                put("EXAMPLE_DATA_POINT", "EXAMPLE_DATA_TITLE");
//                Look at past years' SpecificConstants for further formatting
            }
        };

        Map<String, String> initialDatasToGraphMap = new HashMap<String, String>() {
            {
//              put("DATA_POINT_TO_BE_GRAPHED","DATA_POINT_NEEDED_TO_GRAPH_PRIOR_DATA_POINT");
                put("calculatedData.avgCargoScored", "calculatedData.cargoScored");
                put("calculatedData.avgPanelsScored", "calculatedData.panelsScored");
                put("calculatedData.avgCargoFouls", "calculatedData.cargoFouls");
                put("calculatedData.avgPinningFouls", "calculatedData.pinningFouls");
                put("calculatedData.avgTimeClimbing", "calculatedData.timeClimbing");
                put("calculatedData.avgTimeIncap", "calculatedData.timeIncap");
                put("calculatedData.percentNoShow", "isNoShow");
                put("calculatedData.percentIncap", "calculatedData.timeIncap");
                put("calculatedData.percentImpaired", "calculatedData.timeImpaired");
                put("calculatedData.avgPanelsScoredSandstorm","calculatedData.panelsScoredSandstorm");
                put("calculatedData.avgCargoScoredSandstorm","calculatedData.cargoScoredSandstorm");
                put("calculatedData.panelLoadSuccess","calculatedData.panelLoadSuccess");
                put("calculatedData.cargoSuccessDefended","calculatedData.cargoSuccessDefended");
                put("calculatedData.cargoSuccessL2","calculatedData.cargoSuccessL2");
                put("calculatedData.cargoSuccessL3","calculatedData.cargoSuccessL3");
                put("calculatedData.panelSuccessDefended","calculatedData.panelSuccessDefended");
                put("calculatedData.panelSuccessL2","calculatedData.panelSuccessL2");
                put("calculatedData.panelSuccessL3","calculatedData.panelSuccessL3");
//                put("calculatedData.climbSuccessL2","calculatedData.selfClimbLevel");
//                put("calculatedData.climbSuccessL3","calculatedData.selfClimbLevel");
                put("calculatedData.habLineAttemptsL1", "calculatedData.habLineAttemptsL1");
                put("calculatedData.habLineAttemptsL2", "calculatedData.habLineAttemptsL2");
                put("calculatedData.avgPointsPrevented", "calculatedData.pointsPrevented");
                put("calculatedData.avgCargoPointsPrevented", "calculatedData.cargoPointsPrevented");
                put("calculatedData.avgPanelPointsPrevented", "calculatedData.panelPointsPrevented");
                put("calculatedData.percentDysfunctional","calculatedData.timeIncap");
//                put("calculatedData.habLineSuccessL2","crossedHabLine");
//                put("calculatedData.habLineSuccessL1","crossedHabLine");
                put("calculatedData.avgRankDefense","rankDefense");
                put("calculatedData.avgRankCounterDefense","rankDefense");
                put("calculatedData.failedCyclesCausedPerSecond","calculatedData.failedCyclesCaused");
                put("calculatedData.failedCyclesCaused","calculatedData.totalFailedCyclesCaused");
                put("calculatedData.avgTimeDefending","calculatedData.timeDefending");
                put("calculatedData.totalTimeDefending","calculatedData.timeDefending");
                put("calculatedData.avgFailedCyclesCaused","calculatedData.totalFailedCyclesCaused");
                put("calculatedData.avgPointsPrevented","calculatedData.pointsPrevented");
            }
        };

        Map<String, String> initialDataComparisonDatapointsTEAMSp75 = new HashMap<String, String>() {
            {
                put("p75avgCargoScored", "avg cargo scored");
                put("p75avgPanelsScored", "avg panels scored");
                put("p75avgCargoFouls", "avg cargo foul out of field");
                put("p75panelLoadSuccess", "panel LS success");
                put("p75cargoCycleAll", "avg cargo in RS/CS");
                put("p75cargoCycleL1", "avg cargo in L1 RS");
                put("p75cargoCycleL2", "avg cargo in L2 RS");
                put("p75cargoCycleL3", "avg cargo in L3 RS");
                put("p75panelCycleAll", "avg panel in RS/CS");
                put("p75panelCycleL1", "avg panel in L1 RS");
                put("p75panelCycleL2", "avg panel in L2 RS");
                put("p75panelCycleL3", "avg panel in L3 RS");
                put("p75cargoSuccessAll", "avg cargo all success");
                put("p75cargoSuccessDefended", "avg cargo defended success");
                put("p75cargoSuccessUndefended", "avg cargo undefended success");
                put("p75cargoSuccessL1", "avg cargo success in L1 RS");
                put("p75cargoSuccessL2", "avg cargo success in L2 RS");
                put("p75cargoSuccessL3", "avg cargo success in L3 RS");
                put("p75panelSuccessAll", "avg panel all success");
                put("p75panelSuccessL1", "avg panel success in L1 RS");
                put("p75panelSuccessL2", "avg panel success in L2 RS");
                put("p75panelSuccessL3", "avg panel success in L3 RS");
                put("p75panelSuccessFromSide", "avg panel success from side");
                put("p75habLineSuccessL1", "HAB line success start from L1");
                put("p75habLineSuccessL2", "HAB line success start from L2");
                put("p75avgTimeIncap", "avg time incap");
                put("p75avgTimeClimbing", "avg time climbing");
                put("p75percentIncap", "% incap");
                put("p75percentNoShow", "% no show");
                put("p75AvgPinningFouls", "avg panels spilled");
            }
        };
        Map<String, String> initialDataComparisonDatapointsTEAMSlfm = new HashMap<String, String>() {
            {
                put("lfmAvgCargoScored", "avg cargo scored");
                put("lfmAvgPanelsScored", "avg panel scored");
                put("lfmAvgCargoFouls", "avg cargo fouls");
                put("lfmPanelLoadSuccess", "panel LS success");
                put("lfmCargoCycleAll", "avg cargo RS");
                put("lfmCargoCycleL1", "avg cargo L1 RS/CS");
                put("lfmCargoCycleL2", "avg cargo L2 RS");
                put("lfmCargoCycleL3", "avg cargo L3 RS");
                put("lfmPanelCycleAll", "avg panel RS");
                put("lfmPanelCycleL1", "avg panel L1 RS");
                put("lfmPanelCycleL2", "avg panel L2 RS");
                put("lfmPanelCycleL3", "avg panel L3 RS");
                put("lfmCargoSuccessAll", "cargo all success");
                put("lfmCargoSuccessDefended", "cargo defended success");
                put("lfmCargoSuccessUndefended", "cargo undefended success");
                put("lfmCargoSuccessL1", "avg panel L1 success");
                put("lfmCargoSuccessL2", "avg panel L2 success");
                put("lfmCargoSuccessL3", "avg panel L3 success");
                put("lfmPanelSuccessAll", "avg panel all success");
                put("lfmPanelSuccessDefended", "avg panel defended success");
                put("lfmPanelSuccessUndefended", "avg panel undefended success");
                put("lfmPanelSuccessL1", "avg panel L1 success");
                put("lfmPanelSuccessL2", "avg panel L2 success");
                put("lfmPanelSuccessL3", "avg panel L3 success");
                put("lfmPanelSuccessFromSide", "avg far side RS or side CS placement");
                put("lfmHabLineSuccessL1", "HAB line success start from L1");
                put("lfmHabLineSuccessL2", "HAB line success start from L2");
                put("lfmAvgTimeIncap", "avg time incap");
                put("lfmAvgTimeClimbing", "avg time climbing");
                put("lfmPercentIncap", "% incap");
                put("lfmPercentNoShow", "% no show");
                put("lfmAvgPinningFouls", "avg panels spilled");
            }
        };
        Map<String, String> initialDataComparisonDatapointsTEAMSnormal = new HashMap<String, String>() {
            {
                put("actualRPs", "total # RP");
                put("matchesPlayed", "matches played");
                put("predictedRPs", "predicted PRs");
                put("predictedSeed", "predicted seed");
                put("hasCargoGroundIntake", "has cargo ground intake");
                put("hasPanelGroundIntake", "has panel ground intake");
                put("didPreloadPanel", "preloaded panel at least once");
                put("avgCargoScored", "avg cargo scored");
                put("avgPanelsScored", "avg hatch scored");
                put("avgCargoFouls", "avg cargo fouls out of field");
                put("panelSuccessFromSide", "Far side RS or side CS placements");
                put("habLineSuccessL1", "% HAB line from L1 success");
                put("habLineSuccessL2", "% HAB line from L2 success");
                put("avgTimeIncap", "avg incap time");
                put("avgTimeClimbing", "avg climbing time");
                put("percentIncap", "% incap");
                put("percentNoShow", "% no show");
                put("predictedDedicatedPanelCycles", "predicted only panel cycles");
                put("predictedDedicatedCargoCycles", "predicted only cargo");
                put("predictedSoloPoints", "predicted points by team (alone)");
                put("cargoAbility", "cargo ability");
                put("panelAbility", "panel ability");
                put("firstPickAbility", "first pick ability");
                put("secondPickAbility", "second pick ability");
                put("calculatedData.avgPinningFouls", "avg panels spilled");
            }
        };
        Map<String, String> initialDataComparisonDatapointsTEAMSsd = new HashMap<String, String>() {
            {
                put("sdAvgCargoScored", "avg cargo scored");
                put("sdAvgPanelsScored", "avg hatch scored");
                put("sdAvgCargoFouls", "avg cargo fouls");
                put("sdPanelLoadSuccess", "avg panel LS success");
                put("sdCargoCycleAll", "avg cargo in RS/CS");
                put("sdCargoCycleL1", "avg cargo in L1 RS/CS");
                put("sdCargoCycleL2", "avg cargo in L2 RS");
                put("sdCargoCycleL3", "avg cargo in L3 RS");
                put("sdPanelCycleAll", "avg panel in RC/CS");
                put("sdPanelCycleL1", "avg panel in L1 RC/CS");
                put("sdPanelCycleL2", "avg panel in L2 RC/CS");
                put("sdPanelCycleL3", "avg panel in L3 RC/CS");
                put("sdCargoSuccessAll", "avg cargo all success");
                put("sdCargoSuccessDefended", "avg cargo defended success");
                put("sdCargoSuccessUndefended", "avg cargo undefended success");
                put("sdCargoSuccessL1", "avg cargo success L1");
                put("sdCargoSuccessL2", "avg cargo success L2");
                put("sdCargoSuccessL3", "avg cargo success L3");
                put("sdPanelSuccessAll", "avg panel all success");
                put("sdPanelSuccessDefended", "avg panel defended success");
                put("sdPanelSuccessUndefended", "avg panel undefended success");
                put("sdPanelSuccessL1", "avg cargo success L1");
                put("sdPanelSuccessL2", "avg cargo success L2");
                put("sdPanelSuccessL3", "avg cargo success L3");
                put("sdPanelSuccessFromSide", "avg far side RS or side CS placement");
                put("sdHabLineSuccessL1", "HAB line success start from L1");
                put("sdHabLineSuccessL2", "HAB line success start from L2");
                put("sdAvgTimeIncap", "avg time incap");
                put("sdAvgTimeClimbing", "avg time climbing");
                put("sdPercentIncap", "% incap");
                put("sdPercentNoShow", "% no show");
                put("sdAvgPinningFouls", "avg panels spilled");
            }
        };
        Map<String, String> initialDataComparisonDatapointsTIMD = new HashMap<String, String>() {
            {
                put("cargoScored", "# cargo scored");
                put("panelsScored", "# panel scored");
                put("cargoFouls", "cargo fouls out of field");
                put("panelLoadSuccess", "LS intake success");
                put("cargoCycleAll", "avg cargo in RS/CS");
                put("cargoCycleL1", "avg cargo L1 RS/CS");
                put("cargoCycleL2", "avg cargo L2 RS");
                put("cargoCycleL3", "avg cargo L3 RS");
                put("panelCycleAll", "avg hatch in RS/CS");
                put("panelCycleL1", "avg panel L1 RS/CS");
                put("panelCycleL2", "avg panel L2 RS");
                put("panelCycleL3", "avg panel L3 RS");
                put("cargoSuccessAll", "% cargo total success");
                put("cargoSuccessDefended", "% cargo defend success");
                put("cargoSuccessUndefended", "% cargo undefended success");
                put("cargoSuccessL1", "% cargo success L1 RS/CS");
                put("cargoSuccessL2", "% cargo success L2 RS");
                put("cargoSuccessL3", "% cargo success L3 RS");
                put("panelSuccessAll", "% panel total success");
                put("panelSuccessDefended", "% panel defend success");
                put("panelSuccessUndefended", "% panel undefended success");
                put("panelSuccessL1", "% panel success L1");
                put("panelSuccessL2", "% panel success L2");
                put("panelSuccessL3", "% panel success L3");
                put("timeIncap", "time incap (% of match)");
                put("timeClimbing", "time climbing (s)");
                put("pinningFouls", "panels spilled");
            }
        };
        List<String> categoryList = Arrays.asList(
                "Normal",
                "Last Four Matches",
                "Standard Deviation",
                "75th Percentile");

        KEYS_TO_TITLES = initialKeysToTitlesMap;
        DATA_TO_GRAPH = initialDatasToGraphMap;
        DATA_COMPARISON_TEAMS_SD = initialDataComparisonDatapointsTEAMSsd;
        DATA_COMPARISON_TEAMS_LFM = initialDataComparisonDatapointsTEAMSlfm;
        DATA_COMPARISON_TEAMS_NORMAL = initialDataComparisonDatapointsTEAMSnormal;
        DATA_COMPARISON_TEAMS_P75 = initialDataComparisonDatapointsTEAMSp75;
        DATA_COMPARISON_TIMD = initialDataComparisonDatapointsTIMD;
        CATEGORY_LIST = categoryList;
    }
}
